import Head from 'next/head';

type Props = {
  title: string;
};

const HeadComponent: React.VFC<Props> = ({ title }) => (
  <Head>
    <title>{title}</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
);

export default HeadComponent;
