name: Release Drafter

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, edited]

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ github.token }}
